---
title: "Descriptive Analyses"
output: html_document
---

RUN = *Cmd+Shift+Enter*.  
ADD CHUNK = *Cmd+Option+I*.  
PREVIEW = *Cmd+Shift+K*. 

## Install Packages/Libaries
```{r}
# Install packages
#devtools::install_github("kenhanscombe/ukbtools", dependencies = TRUE)

# Add libraries
library(ukbtools)
```

## Load up data
```{r}
# Create data frames for second data release
my_ukb_data <- ukb_df("ukb40721")
dim(my_ukb_data)
```

## Define constants
```{r}
num_diagnosis_icd10 <- 410282
num_cancer_icd10 <- 83480
num_diagnosis_self <- 375054
num_cancer_self <- 41698

# Create list of all possible indicies
all_indices <- seq(1, nrow(my_ukb_data), 1)
```

## Add extra variables to dataframe as needed
```{r}
# Add birthday variable, in R date format
my_ukb_data$birthday <- as.Date(sprintf("%d-%s-%d", my_ukb_data$year_of_birth_f34_0_0, 
                                        my_ukb_data$month_of_birth_f52_0_0,1), format="%Y-%B-%d")
# Add age
my_ukb_data$age_years <- floor((Sys.Date() - my_ukb_data$birthday)/365.25)
```

## Define disease column indices
```{r}
# Define all necessary disease columns for IDC10. Arrays 0-65. Field 41270.
col_disease_icd10 <- c("diagnoses_icd10_f41270_0_0","diagnoses_icd10_f41270_0_1",
                       "diagnoses_icd10_f41270_0_2","diagnoses_icd10_f41270_0_3",
                       "diagnoses_icd10_f41270_0_4","diagnoses_icd10_f41270_0_5",
                       "diagnoses_icd10_f41270_0_6","diagnoses_icd10_f41270_0_7",
                       "diagnoses_icd10_f41270_0_8","diagnoses_icd10_f41270_0_9",
                       "diagnoses_icd10_f41270_0_10","diagnoses_icd10_f41270_0_11",
                       "diagnoses_icd10_f41270_0_12","diagnoses_icd10_f41270_0_13",
                       "diagnoses_icd10_f41270_0_14","diagnoses_icd10_f41270_0_15",
                       "diagnoses_icd10_f41270_0_16","diagnoses_icd10_f41270_0_17",
                       "diagnoses_icd10_f41270_0_18","diagnoses_icd10_f41270_0_19",
                       "diagnoses_icd10_f41270_0_20","diagnoses_icd10_f41270_0_21",
                       "diagnoses_icd10_f41270_0_22","diagnoses_icd10_f41270_0_23",
                       "diagnoses_icd10_f41270_0_24","diagnoses_icd10_f41270_0_25",
                       "diagnoses_icd10_f41270_0_26","diagnoses_icd10_f41270_0_27",
                       "diagnoses_icd10_f41270_0_28","diagnoses_icd10_f41270_0_29",
                       "diagnoses_icd10_f41270_0_30","diagnoses_icd10_f41270_0_31",
                       "diagnoses_icd10_f41270_0_32","diagnoses_icd10_f41270_0_33",
                       "diagnoses_icd10_f41270_0_34","diagnoses_icd10_f41270_0_35",
                       "diagnoses_icd10_f41270_0_36","diagnoses_icd10_f41270_0_37",
                       "diagnoses_icd10_f41270_0_38","diagnoses_icd10_f41270_0_39",
                       "diagnoses_icd10_f41270_0_40","diagnoses_icd10_f41270_0_41",
                       "diagnoses_icd10_f41270_0_42","diagnoses_icd10_f41270_0_43",
                       "diagnoses_icd10_f41270_0_44","diagnoses_icd10_f41270_0_45",
                       "diagnoses_icd10_f41270_0_46","diagnoses_icd10_f41270_0_47",
                       "diagnoses_icd10_f41270_0_48","diagnoses_icd10_f41270_0_49",
                       "diagnoses_icd10_f41270_0_50","diagnoses_icd10_f41270_0_51",
                       "diagnoses_icd10_f41270_0_52","diagnoses_icd10_f41270_0_53",
                       "diagnoses_icd10_f41270_0_54","diagnoses_icd10_f41270_0_55",
                       "diagnoses_icd10_f41270_0_56","diagnoses_icd10_f41270_0_57",
                       "diagnoses_icd10_f41270_0_58","diagnoses_icd10_f41270_0_59",
                       "diagnoses_icd10_f41270_0_60","diagnoses_icd10_f41270_0_61",
                       "diagnoses_icd10_f41270_0_62","diagnoses_icd10_f41270_0_63",
                       "diagnoses_icd10_f41270_0_64","diagnoses_icd10_f41270_0_65",
                       "diagnoses_icd10_f41270_0_66","diagnoses_icd10_f41270_0_67",
                       "diagnoses_icd10_f41270_0_68","diagnoses_icd10_f41270_0_69",
                       "diagnoses_icd10_f41270_0_70","diagnoses_icd10_f41270_0_71",
                       "diagnoses_icd10_f41270_0_72","diagnoses_icd10_f41270_0_73",
                       "diagnoses_icd10_f41270_0_74","diagnoses_icd10_f41270_0_75",
                       "diagnoses_icd10_f41270_0_76","diagnoses_icd10_f41270_0_77",
                       "diagnoses_icd10_f41270_0_78","diagnoses_icd10_f41270_0_79",
                       "diagnoses_icd10_f41270_0_80","diagnoses_icd10_f41270_0_81",
                       "diagnoses_icd10_f41270_0_82","diagnoses_icd10_f41270_0_83",
                       "diagnoses_icd10_f41270_0_84","diagnoses_icd10_f41270_0_85",
                       "diagnoses_icd10_f41270_0_86","diagnoses_icd10_f41270_0_87",
                       "diagnoses_icd10_f41270_0_88","diagnoses_icd10_f41270_0_89",
                       "diagnoses_icd10_f41270_0_90","diagnoses_icd10_f41270_0_91",
                       "diagnoses_icd10_f41270_0_92","diagnoses_icd10_f41270_0_93",
                       "diagnoses_icd10_f41270_0_94","diagnoses_icd10_f41270_0_95",
                       "diagnoses_icd10_f41270_0_96","diagnoses_icd10_f41270_0_97",
                       "diagnoses_icd10_f41270_0_98","diagnoses_icd10_f41270_0_99",
                       "diagnoses_icd10_f41270_0_100","diagnoses_icd10_f41270_0_101",
                       "diagnoses_icd10_f41270_0_102","diagnoses_icd10_f41270_0_103",
                       "diagnoses_icd10_f41270_0_104","diagnoses_icd10_f41270_0_105",
                       "diagnoses_icd10_f41270_0_106","diagnoses_icd10_f41270_0_107",
                       "diagnoses_icd10_f41270_0_108","diagnoses_icd10_f41270_0_109",
                       "diagnoses_icd10_f41270_0_110","diagnoses_icd10_f41270_0_111",
                       "diagnoses_icd10_f41270_0_112","diagnoses_icd10_f41270_0_113",
                       "diagnoses_icd10_f41270_0_114","diagnoses_icd10_f41270_0_115",
                       "diagnoses_icd10_f41270_0_116","diagnoses_icd10_f41270_0_117",
                       "diagnoses_icd10_f41270_0_118","diagnoses_icd10_f41270_0_119",
                       "diagnoses_icd10_f41270_0_120","diagnoses_icd10_f41270_0_121",
                       "diagnoses_icd10_f41270_0_122","diagnoses_icd10_f41270_0_123",
                       "diagnoses_icd10_f41270_0_124","diagnoses_icd10_f41270_0_125",
                       "diagnoses_icd10_f41270_0_126","diagnoses_icd10_f41270_0_127",
                       "diagnoses_icd10_f41270_0_128","diagnoses_icd10_f41270_0_129",
                       "diagnoses_icd10_f41270_0_130","diagnoses_icd10_f41270_0_131",
                       "diagnoses_icd10_f41270_0_132","diagnoses_icd10_f41270_0_133",
                       "diagnoses_icd10_f41270_0_134","diagnoses_icd10_f41270_0_135",
                       "diagnoses_icd10_f41270_0_136","diagnoses_icd10_f41270_0_137",
                       "diagnoses_icd10_f41270_0_138","diagnoses_icd10_f41270_0_139",
                       "diagnoses_icd10_f41270_0_140","diagnoses_icd10_f41270_0_141",
                       "diagnoses_icd10_f41270_0_142","diagnoses_icd10_f41270_0_143",
                       "diagnoses_icd10_f41270_0_144","diagnoses_icd10_f41270_0_145",
                       "diagnoses_icd10_f41270_0_146","diagnoses_icd10_f41270_0_147",
                       "diagnoses_icd10_f41270_0_148","diagnoses_icd10_f41270_0_149",
                       "diagnoses_icd10_f41270_0_150","diagnoses_icd10_f41270_0_151",
                       "diagnoses_icd10_f41270_0_152","diagnoses_icd10_f41270_0_153",
                       "diagnoses_icd10_f41270_0_154","diagnoses_icd10_f41270_0_155",
                       "diagnoses_icd10_f41270_0_156","diagnoses_icd10_f41270_0_157",
                       "diagnoses_icd10_f41270_0_158","diagnoses_icd10_f41270_0_159",
                       "diagnoses_icd10_f41270_0_160","diagnoses_icd10_f41270_0_161",
                       "diagnoses_icd10_f41270_0_162","diagnoses_icd10_f41270_0_163",
                       "diagnoses_icd10_f41270_0_164","diagnoses_icd10_f41270_0_165",
                       "diagnoses_icd10_f41270_0_166","diagnoses_icd10_f41270_0_167",
                       "diagnoses_icd10_f41270_0_168","diagnoses_icd10_f41270_0_169",
                       "diagnoses_icd10_f41270_0_170","diagnoses_icd10_f41270_0_171",
                       "diagnoses_icd10_f41270_0_172","diagnoses_icd10_f41270_0_173",
                       "diagnoses_icd10_f41270_0_174","diagnoses_icd10_f41270_0_175",
                       "diagnoses_icd10_f41270_0_176","diagnoses_icd10_f41270_0_177",
                       "diagnoses_icd10_f41270_0_178","diagnoses_icd10_f41270_0_179",
                       "diagnoses_icd10_f41270_0_180","diagnoses_icd10_f41270_0_181",
                       "diagnoses_icd10_f41270_0_182","diagnoses_icd10_f41270_0_183",
                       "diagnoses_icd10_f41270_0_184","diagnoses_icd10_f41270_0_185",
                       "diagnoses_icd10_f41270_0_186","diagnoses_icd10_f41270_0_187",
                       "diagnoses_icd10_f41270_0_188","diagnoses_icd10_f41270_0_189",
                       "diagnoses_icd10_f41270_0_190","diagnoses_icd10_f41270_0_191",
                       "diagnoses_icd10_f41270_0_192","diagnoses_icd10_f41270_0_193",
                       "diagnoses_icd10_f41270_0_194","diagnoses_icd10_f41270_0_195",
                       "diagnoses_icd10_f41270_0_196","diagnoses_icd10_f41270_0_197",
                       "diagnoses_icd10_f41270_0_198","diagnoses_icd10_f41270_0_199",
                       "diagnoses_icd10_f41270_0_200","diagnoses_icd10_f41270_0_201",
                       "diagnoses_icd10_f41270_0_202","diagnoses_icd10_f41270_0_203",
                       "diagnoses_icd10_f41270_0_204","diagnoses_icd10_f41270_0_205",
                       "diagnoses_icd10_f41270_0_206","diagnoses_icd10_f41270_0_207",
                       "diagnoses_icd10_f41270_0_208","diagnoses_icd10_f41270_0_209",
                       "diagnoses_icd10_f41270_0_210","diagnoses_icd10_f41270_0_211",
                       "diagnoses_icd10_f41270_0_212")

# Define all necessary disease columns for main IDC10 diagnosis. Arrays 0-65. Field 41270.
col_main_icd10 <- c("diagnoses_main_icd10_f41202_0_0","diagnoses_main_icd10_f41202_0_1",
                       "diagnoses_main_icd10_f41202_0_2","diagnoses_main_icd10_f41202_0_3",
                       "diagnoses_main_icd10_f41202_0_4","diagnoses_main_icd10_f41202_0_5",
                       "diagnoses_main_icd10_f41202_0_6","diagnoses_main_icd10_f41202_0_7",
                       "diagnoses_main_icd10_f41202_0_8","diagnoses_main_icd10_f41202_0_9",
                       "diagnoses_main_icd10_f41202_0_10","diagnoses_main_icd10_f41202_0_11",
                       "diagnoses_main_icd10_f41202_0_12","diagnoses_main_icd10_f41202_0_13",
                       "diagnoses_main_icd10_f41202_0_14","diagnoses_main_icd10_f41202_0_15",
                       "diagnoses_main_icd10_f41202_0_16","diagnoses_main_icd10_f41202_0_17",
                       "diagnoses_main_icd10_f41202_0_18","diagnoses_main_icd10_f41202_0_19",
                       "diagnoses_main_icd10_f41202_0_20","diagnoses_main_icd10_f41202_0_21",
                       "diagnoses_main_icd10_f41202_0_22","diagnoses_main_icd10_f41202_0_23",
                       "diagnoses_main_icd10_f41202_0_24","diagnoses_main_icd10_f41202_0_25",
                       "diagnoses_main_icd10_f41202_0_26","diagnoses_main_icd10_f41202_0_27",
                       "diagnoses_main_icd10_f41202_0_28","diagnoses_main_icd10_f41202_0_29",
                       "diagnoses_main_icd10_f41202_0_30","diagnoses_main_icd10_f41202_0_31",
                       "diagnoses_main_icd10_f41202_0_32","diagnoses_main_icd10_f41202_0_33",
                       "diagnoses_main_icd10_f41202_0_34","diagnoses_main_icd10_f41202_0_35",
                       "diagnoses_main_icd10_f41202_0_36","diagnoses_main_icd10_f41202_0_37",
                       "diagnoses_main_icd10_f41202_0_38","diagnoses_main_icd10_f41202_0_39",
                       "diagnoses_main_icd10_f41202_0_40","diagnoses_main_icd10_f41202_0_41",
                       "diagnoses_main_icd10_f41202_0_42","diagnoses_main_icd10_f41202_0_43",
                       "diagnoses_main_icd10_f41202_0_44","diagnoses_main_icd10_f41202_0_45",
                       "diagnoses_main_icd10_f41202_0_46","diagnoses_main_icd10_f41202_0_47",
                       "diagnoses_main_icd10_f41202_0_48","diagnoses_main_icd10_f41202_0_49",
                       "diagnoses_main_icd10_f41202_0_50","diagnoses_main_icd10_f41202_0_51",
                       "diagnoses_main_icd10_f41202_0_52","diagnoses_main_icd10_f41202_0_53",
                       "diagnoses_main_icd10_f41202_0_54","diagnoses_main_icd10_f41202_0_55",
                       "diagnoses_main_icd10_f41202_0_56","diagnoses_main_icd10_f41202_0_57",
                       "diagnoses_main_icd10_f41202_0_58","diagnoses_main_icd10_f41202_0_59",
                       "diagnoses_main_icd10_f41202_0_60","diagnoses_main_icd10_f41202_0_61",
                       "diagnoses_main_icd10_f41202_0_62","diagnoses_main_icd10_f41202_0_63",
                       "diagnoses_main_icd10_f41202_0_64","diagnoses_main_icd10_f41202_0_65")

col_second_icd10 <- c("diagnoses_secondary_icd10_f41204_0_0", "diagnoses_secondary_icd10_f41204_0_1",
                      "diagnoses_secondary_icd10_f41204_0_2", "diagnoses_secondary_icd10_f41204_0_3",
                      "diagnoses_secondary_icd10_f41204_0_4", "diagnoses_secondary_icd10_f41204_0_5",
                      "diagnoses_secondary_icd10_f41204_0_6", "diagnoses_secondary_icd10_f41204_0_7",
                      "diagnoses_secondary_icd10_f41204_0_8", "diagnoses_secondary_icd10_f41204_0_9",
                      "diagnoses_secondary_icd10_f41204_0_10", "diagnoses_secondary_icd10_f41204_0_11",
                      "diagnoses_secondary_icd10_f41204_0_12", "diagnoses_secondary_icd10_f41204_0_13",
                      "diagnoses_secondary_icd10_f41204_0_14", "diagnoses_secondary_icd10_f41204_0_15",
                      "diagnoses_secondary_icd10_f41204_0_16", "diagnoses_secondary_icd10_f41204_0_17",
                      "diagnoses_secondary_icd10_f41204_0_18", "diagnoses_secondary_icd10_f41204_0_19",
                      "diagnoses_secondary_icd10_f41204_0_20", "diagnoses_secondary_icd10_f41204_0_21",
                      "diagnoses_secondary_icd10_f41204_0_22", "diagnoses_secondary_icd10_f41204_0_23",
                      "diagnoses_secondary_icd10_f41204_0_24", "diagnoses_secondary_icd10_f41204_0_25",
                      "diagnoses_secondary_icd10_f41204_0_26", "diagnoses_secondary_icd10_f41204_0_27",
                      "diagnoses_secondary_icd10_f41204_0_28", "diagnoses_secondary_icd10_f41204_0_29",
                      "diagnoses_secondary_icd10_f41204_0_30", "diagnoses_secondary_icd10_f41204_0_31",
                      "diagnoses_secondary_icd10_f41204_0_32", "diagnoses_secondary_icd10_f41204_0_33",
                      "diagnoses_secondary_icd10_f41204_0_34", "diagnoses_secondary_icd10_f41204_0_35",
                      "diagnoses_secondary_icd10_f41204_0_36", "diagnoses_secondary_icd10_f41204_0_37",
                      "diagnoses_secondary_icd10_f41204_0_38", "diagnoses_secondary_icd10_f41204_0_39",
                      "diagnoses_secondary_icd10_f41204_0_40", "diagnoses_secondary_icd10_f41204_0_41",
                      "diagnoses_secondary_icd10_f41204_0_42", "diagnoses_secondary_icd10_f41204_0_43",
                      "diagnoses_secondary_icd10_f41204_0_44", "diagnoses_secondary_icd10_f41204_0_45",
                      "diagnoses_secondary_icd10_f41204_0_46", "diagnoses_secondary_icd10_f41204_0_47",
                      "diagnoses_secondary_icd10_f41204_0_48", "diagnoses_secondary_icd10_f41204_0_49",
                      "diagnoses_secondary_icd10_f41204_0_50", "diagnoses_secondary_icd10_f41204_0_51",
                      "diagnoses_secondary_icd10_f41204_0_52", "diagnoses_secondary_icd10_f41204_0_53",
                      "diagnoses_secondary_icd10_f41204_0_54", "diagnoses_secondary_icd10_f41204_0_55",
                      "diagnoses_secondary_icd10_f41204_0_56", "diagnoses_secondary_icd10_f41204_0_57",
                      "diagnoses_secondary_icd10_f41204_0_58", "diagnoses_secondary_icd10_f41204_0_59",
                      "diagnoses_secondary_icd10_f41204_0_60", "diagnoses_secondary_icd10_f41204_0_61",
                      "diagnoses_secondary_icd10_f41204_0_62", "diagnoses_secondary_icd10_f41204_0_63",
                      "diagnoses_secondary_icd10_f41204_0_64", "diagnoses_secondary_icd10_f41204_0_65",
                      "diagnoses_secondary_icd10_f41204_0_66", "diagnoses_secondary_icd10_f41204_0_67",
                      "diagnoses_secondary_icd10_f41204_0_68", "diagnoses_secondary_icd10_f41204_0_69",
                      "diagnoses_secondary_icd10_f41204_0_70", "diagnoses_secondary_icd10_f41204_0_71",
                      "diagnoses_secondary_icd10_f41204_0_72", "diagnoses_secondary_icd10_f41204_0_73",
                      "diagnoses_secondary_icd10_f41204_0_74", "diagnoses_secondary_icd10_f41204_0_75",
                      "diagnoses_secondary_icd10_f41204_0_76", "diagnoses_secondary_icd10_f41204_0_77",
                      "diagnoses_secondary_icd10_f41204_0_78", "diagnoses_secondary_icd10_f41204_0_79",
                      "diagnoses_secondary_icd10_f41204_0_80", "diagnoses_secondary_icd10_f41204_0_81",
                      "diagnoses_secondary_icd10_f41204_0_82", "diagnoses_secondary_icd10_f41204_0_83",
                      "diagnoses_secondary_icd10_f41204_0_84", "diagnoses_secondary_icd10_f41204_0_85",
                      "diagnoses_secondary_icd10_f41204_0_86", "diagnoses_secondary_icd10_f41204_0_87",
                      "diagnoses_secondary_icd10_f41204_0_88", "diagnoses_secondary_icd10_f41204_0_89",
                      "diagnoses_secondary_icd10_f41204_0_90", "diagnoses_secondary_icd10_f41204_0_91",
                      "diagnoses_secondary_icd10_f41204_0_92", "diagnoses_secondary_icd10_f41204_0_93",
                      "diagnoses_secondary_icd10_f41204_0_94", "diagnoses_secondary_icd10_f41204_0_95",
                      "diagnoses_secondary_icd10_f41204_0_96", "diagnoses_secondary_icd10_f41204_0_97",
                      "diagnoses_secondary_icd10_f41204_0_98", "diagnoses_secondary_icd10_f41204_0_99",
                      "diagnoses_secondary_icd10_f41204_0_100", "diagnoses_secondary_icd10_f41204_0_101",
                      "diagnoses_secondary_icd10_f41204_0_102", "diagnoses_secondary_icd10_f41204_0_103",
                      "diagnoses_secondary_icd10_f41204_0_104", "diagnoses_secondary_icd10_f41204_0_105",
                      "diagnoses_secondary_icd10_f41204_0_106", "diagnoses_secondary_icd10_f41204_0_107",
                      "diagnoses_secondary_icd10_f41204_0_108", "diagnoses_secondary_icd10_f41204_0_109",
                      "diagnoses_secondary_icd10_f41204_0_110", "diagnoses_secondary_icd10_f41204_0_111",
                      "diagnoses_secondary_icd10_f41204_0_112", "diagnoses_secondary_icd10_f41204_0_113",
                      "diagnoses_secondary_icd10_f41204_0_114", "diagnoses_secondary_icd10_f41204_0_115",
                      "diagnoses_secondary_icd10_f41204_0_116", "diagnoses_secondary_icd10_f41204_0_117",
                      "diagnoses_secondary_icd10_f41204_0_118", "diagnoses_secondary_icd10_f41204_0_119",
                      "diagnoses_secondary_icd10_f41204_0_120", "diagnoses_secondary_icd10_f41204_0_121",
                      "diagnoses_secondary_icd10_f41204_0_122", "diagnoses_secondary_icd10_f41204_0_123",
                      "diagnoses_secondary_icd10_f41204_0_124", "diagnoses_secondary_icd10_f41204_0_125",
                      "diagnoses_secondary_icd10_f41204_0_126", "diagnoses_secondary_icd10_f41204_0_127",
                      "diagnoses_secondary_icd10_f41204_0_128", "diagnoses_secondary_icd10_f41204_0_129",
                      "diagnoses_secondary_icd10_f41204_0_130", "diagnoses_secondary_icd10_f41204_0_131",
                      "diagnoses_secondary_icd10_f41204_0_132", "diagnoses_secondary_icd10_f41204_0_133",
                      "diagnoses_secondary_icd10_f41204_0_134", "diagnoses_secondary_icd10_f41204_0_135",
                      "diagnoses_secondary_icd10_f41204_0_136", "diagnoses_secondary_icd10_f41204_0_137",
                      "diagnoses_secondary_icd10_f41204_0_138", "diagnoses_secondary_icd10_f41204_0_139",
                      "diagnoses_secondary_icd10_f41204_0_140", "diagnoses_secondary_icd10_f41204_0_141",
                      "diagnoses_secondary_icd10_f41204_0_142", "diagnoses_secondary_icd10_f41204_0_143",
                      "diagnoses_secondary_icd10_f41204_0_144", "diagnoses_secondary_icd10_f41204_0_145",
                      "diagnoses_secondary_icd10_f41204_0_146", "diagnoses_secondary_icd10_f41204_0_147",
                      "diagnoses_secondary_icd10_f41204_0_148", "diagnoses_secondary_icd10_f41204_0_149",
                      "diagnoses_secondary_icd10_f41204_0_150", "diagnoses_secondary_icd10_f41204_0_151",
                      "diagnoses_secondary_icd10_f41204_0_152", "diagnoses_secondary_icd10_f41204_0_153",
                      "diagnoses_secondary_icd10_f41204_0_154", "diagnoses_secondary_icd10_f41204_0_155",
                      "diagnoses_secondary_icd10_f41204_0_156", "diagnoses_secondary_icd10_f41204_0_157",
                      "diagnoses_secondary_icd10_f41204_0_158", "diagnoses_secondary_icd10_f41204_0_159",
                      "diagnoses_secondary_icd10_f41204_0_160", "diagnoses_secondary_icd10_f41204_0_161",
                      "diagnoses_secondary_icd10_f41204_0_162", "diagnoses_secondary_icd10_f41204_0_163",
                      "diagnoses_secondary_icd10_f41204_0_164", "diagnoses_secondary_icd10_f41204_0_165",
                      "diagnoses_secondary_icd10_f41204_0_166", "diagnoses_secondary_icd10_f41204_0_167",
                      "diagnoses_secondary_icd10_f41204_0_168", "diagnoses_secondary_icd10_f41204_0_169",
                      "diagnoses_secondary_icd10_f41204_0_170", "diagnoses_secondary_icd10_f41204_0_171",
                      "diagnoses_secondary_icd10_f41204_0_172", "diagnoses_secondary_icd10_f41204_0_173",
                      "diagnoses_secondary_icd10_f41204_0_174", "diagnoses_secondary_icd10_f41204_0_175",
                      "diagnoses_secondary_icd10_f41204_0_176", "diagnoses_secondary_icd10_f41204_0_177",
                      "diagnoses_secondary_icd10_f41204_0_178", "diagnoses_secondary_icd10_f41204_0_179",
                      "diagnoses_secondary_icd10_f41204_0_180", "diagnoses_secondary_icd10_f41204_0_181",
                      "diagnoses_secondary_icd10_f41204_0_182", "diagnoses_secondary_icd10_f41204_0_183"
                      )

# Define all necessary disease columns for self-reporting. Instances 0-2, Arrays 0-33. Field 20002.
col_disease_self <- c("noncancer_illness_code_selfreported_f20002_0_0",
                      "noncancer_illness_code_selfreported_f20002_0_1",
                      "noncancer_illness_code_selfreported_f20002_0_2",
                      "noncancer_illness_code_selfreported_f20002_0_3",
                      "noncancer_illness_code_selfreported_f20002_0_4",
                      "noncancer_illness_code_selfreported_f20002_0_5",
                      "noncancer_illness_code_selfreported_f20002_0_6",
                      "noncancer_illness_code_selfreported_f20002_0_7",
                      "noncancer_illness_code_selfreported_f20002_0_8",
                      "noncancer_illness_code_selfreported_f20002_0_9",
                      "noncancer_illness_code_selfreported_f20002_0_10",
                      "noncancer_illness_code_selfreported_f20002_0_11",
                      "noncancer_illness_code_selfreported_f20002_0_12",
                      "noncancer_illness_code_selfreported_f20002_0_13",
                      "noncancer_illness_code_selfreported_f20002_0_14",
                      "noncancer_illness_code_selfreported_f20002_0_15",
                      "noncancer_illness_code_selfreported_f20002_0_16",
                      "noncancer_illness_code_selfreported_f20002_0_17",
                      "noncancer_illness_code_selfreported_f20002_0_18",
                      "noncancer_illness_code_selfreported_f20002_0_19",
                      "noncancer_illness_code_selfreported_f20002_0_20",
                      "noncancer_illness_code_selfreported_f20002_0_21",
                      "noncancer_illness_code_selfreported_f20002_0_22",
                      "noncancer_illness_code_selfreported_f20002_0_23",
                      "noncancer_illness_code_selfreported_f20002_0_24",
                      "noncancer_illness_code_selfreported_f20002_0_25",
                      "noncancer_illness_code_selfreported_f20002_0_26",
                      "noncancer_illness_code_selfreported_f20002_0_27",
                      "noncancer_illness_code_selfreported_f20002_0_28",
                      "noncancer_illness_code_selfreported_f20002_0_29",
                      "noncancer_illness_code_selfreported_f20002_0_30",
                      "noncancer_illness_code_selfreported_f20002_0_31",
                      "noncancer_illness_code_selfreported_f20002_0_32",
                      "noncancer_illness_code_selfreported_f20002_0_33",
                      "noncancer_illness_code_selfreported_f20002_1_0",
                      "noncancer_illness_code_selfreported_f20002_1_1",
                      "noncancer_illness_code_selfreported_f20002_1_2",
                      "noncancer_illness_code_selfreported_f20002_1_3",
                      "noncancer_illness_code_selfreported_f20002_1_4",
                      "noncancer_illness_code_selfreported_f20002_1_5",
                      "noncancer_illness_code_selfreported_f20002_1_6",
                      "noncancer_illness_code_selfreported_f20002_1_7",
                      "noncancer_illness_code_selfreported_f20002_1_8",
                      "noncancer_illness_code_selfreported_f20002_1_9",
                      "noncancer_illness_code_selfreported_f20002_1_10",
                      "noncancer_illness_code_selfreported_f20002_1_11",
                      "noncancer_illness_code_selfreported_f20002_1_12",
                      "noncancer_illness_code_selfreported_f20002_1_13",
                      "noncancer_illness_code_selfreported_f20002_1_14",
                      "noncancer_illness_code_selfreported_f20002_1_15",
                      "noncancer_illness_code_selfreported_f20002_1_16",
                      "noncancer_illness_code_selfreported_f20002_1_17",
                      "noncancer_illness_code_selfreported_f20002_1_18",
                      "noncancer_illness_code_selfreported_f20002_1_19",
                      "noncancer_illness_code_selfreported_f20002_1_20",
                      "noncancer_illness_code_selfreported_f20002_1_21",
                      "noncancer_illness_code_selfreported_f20002_1_22",
                      "noncancer_illness_code_selfreported_f20002_1_23",
                      "noncancer_illness_code_selfreported_f20002_1_24",
                      "noncancer_illness_code_selfreported_f20002_1_25",
                      "noncancer_illness_code_selfreported_f20002_1_26",
                      "noncancer_illness_code_selfreported_f20002_1_27",
                      "noncancer_illness_code_selfreported_f20002_1_28",
                      "noncancer_illness_code_selfreported_f20002_1_29",
                      "noncancer_illness_code_selfreported_f20002_1_30",
                      "noncancer_illness_code_selfreported_f20002_1_31",
                      "noncancer_illness_code_selfreported_f20002_1_32",
                      "noncancer_illness_code_selfreported_f20002_1_33",
                      "noncancer_illness_code_selfreported_f20002_2_0",
                      "noncancer_illness_code_selfreported_f20002_2_1",
                      "noncancer_illness_code_selfreported_f20002_2_2",
                      "noncancer_illness_code_selfreported_f20002_2_3",
                      "noncancer_illness_code_selfreported_f20002_2_4",
                      "noncancer_illness_code_selfreported_f20002_2_5",
                      "noncancer_illness_code_selfreported_f20002_2_6",
                      "noncancer_illness_code_selfreported_f20002_2_7",
                      "noncancer_illness_code_selfreported_f20002_2_8",
                      "noncancer_illness_code_selfreported_f20002_2_9",
                      "noncancer_illness_code_selfreported_f20002_2_10",
                      "noncancer_illness_code_selfreported_f20002_2_11",
                      "noncancer_illness_code_selfreported_f20002_2_12",
                      "noncancer_illness_code_selfreported_f20002_2_13",
                      "noncancer_illness_code_selfreported_f20002_2_14",
                      "noncancer_illness_code_selfreported_f20002_2_15",
                      "noncancer_illness_code_selfreported_f20002_2_16",
                      "noncancer_illness_code_selfreported_f20002_2_17",
                      "noncancer_illness_code_selfreported_f20002_2_18",
                      "noncancer_illness_code_selfreported_f20002_2_19",
                      "noncancer_illness_code_selfreported_f20002_2_20",
                      "noncancer_illness_code_selfreported_f20002_2_21",
                      "noncancer_illness_code_selfreported_f20002_2_22",
                      "noncancer_illness_code_selfreported_f20002_2_23",
                      "noncancer_illness_code_selfreported_f20002_2_24",
                      "noncancer_illness_code_selfreported_f20002_2_25",
                      "noncancer_illness_code_selfreported_f20002_2_26",
                      "noncancer_illness_code_selfreported_f20002_2_27",
                      "noncancer_illness_code_selfreported_f20002_2_28",
                      "noncancer_illness_code_selfreported_f20002_2_29",
                      "noncancer_illness_code_selfreported_f20002_2_30",
                      "noncancer_illness_code_selfreported_f20002_2_31",
                      "noncancer_illness_code_selfreported_f20002_2_32",
                      "noncancer_illness_code_selfreported_f20002_2_33")

# Define all necessary cancer columns for IDC10. Instances 0-16. Field 40006.
col_cancer_icd10 <- c("type_of_cancer_icd10_f40006_0_0","type_of_cancer_icd10_f40006_1_0",
                      "type_of_cancer_icd10_f40006_2_0","type_of_cancer_icd10_f40006_3_0",
                      "type_of_cancer_icd10_f40006_4_0","type_of_cancer_icd10_f40006_5_0",
                      "type_of_cancer_icd10_f40006_6_0","type_of_cancer_icd10_f40006_7_0",
                      "type_of_cancer_icd10_f40006_8_0","type_of_cancer_icd10_f40006_9_0",
                      "type_of_cancer_icd10_f40006_10_0","type_of_cancer_icd10_f40006_11_0",
                      "type_of_cancer_icd10_f40006_12_0","type_of_cancer_icd10_f40006_13_0",
                      "type_of_cancer_icd10_f40006_14_0","type_of_cancer_icd10_f40006_14_0",
                      "type_of_cancer_icd10_f40006_16_0")

# Define all necessary cancer columns for self-reporting. Intances 0-2, Arrays 0-5. Field 20001.
col_cancer_self <- c("cancer_code_selfreported_f20001_0_0",
                     "cancer_code_selfreported_f20001_0_1",
                     "cancer_code_selfreported_f20001_0_2",
                     "cancer_code_selfreported_f20001_0_3",
                     "cancer_code_selfreported_f20001_0_4",
                     "cancer_code_selfreported_f20001_0_5",
                     "cancer_code_selfreported_f20001_1_0",
                     "cancer_code_selfreported_f20001_1_1",
                     "cancer_code_selfreported_f20001_1_2",
                     "cancer_code_selfreported_f20001_1_3",
                     "cancer_code_selfreported_f20001_1_4",
                     "cancer_code_selfreported_f20001_1_5",
                     "cancer_code_selfreported_f20001_2_0",
                     "cancer_code_selfreported_f20001_2_1",
                     "cancer_code_selfreported_f20001_2_2",
                     "cancer_code_selfreported_f20001_2_3",
                     "cancer_code_selfreported_f20001_2_4",
                     "cancer_code_selfreported_f20001_2_5")
```

## Grab data frame indices
```{r}
# CF ICD10
# Extract patients with K850-K859 acute pancreatitis designation via ICD 10
cf_conditions_icd10 <- c("E84","E840","E841","E8411","E8419","E848", "E849")
#cf_icd10_e84x <- which(rowSums(sapply(my_ukb_data[,col_main_icd10],"%in%", cf_conditions_icd10))>0)
cf_icd10_e84x <- which(rowSums(sapply(my_ukb_data[,col_second_icd10],"%in%", cf_conditions_icd10))>0)
#cf_icd10_e84x <- which(rowSums(sapply(my_ukb_data[,col_disease_icd10],"%in%", cf_conditions_icd10))>0)
paste0("# with ICD10 CF ", length(cf_icd10_e84x))

# AP ICD10
# Extract patients with K850-K859 acute pancreatitis designation via ICD 10
ap_conditions_icd10 <- c("K85","K850","K851","K852","K853", "K858", "K859")
#ap_icd10_k85x <- which(rowSums(sapply(my_ukb_data[,col_main_icd10],"%in%", ap_conditions_icd10))>0)
ap_icd10_k85x <- which(rowSums(sapply(my_ukb_data[,col_second_icd10],"%in%", ap_conditions_icd10))>0)
#ap_icd10_k85x <- which(rowSums(sapply(my_ukb_data[,col_disease_icd10],"%in%", ap_conditions_icd10))>0)
paste0("# with ICD10 AP ", length(ap_icd10_k85x))

# CP ICD10
# Extract patients with K860-861 chronic pancreatitis designation via ICD 10
cp_conditions_icd10 <- c("K860","K861")
#cp_icd10_k86x <- which(rowSums(sapply(my_ukb_data[,col_main_icd10],"%in%", cp_conditions_icd10))>0)
cp_icd10_k86x <- which(rowSums(sapply(my_ukb_data[,col_second_icd10],"%in%", cp_conditions_icd10))>0)
#cp_icd10_k86x <- which(rowSums(sapply(my_ukb_data[,col_disease_icd10],"%in%", cp_conditions_icd10))>0)
paste0("# with ICD10 CP ", length(cp_icd10_k86x))

# AP & CP ICD10
panc_idc10_ix <- sort(union(ap_icd10_k85x, cp_icd10_k86x))
paste0("# with ICD10 AP or CP ", length(panc_idc10_ix))
paste0("# with both ICD10 AP and CP ", length(intersect(ap_icd10_k85x, cp_icd10_k86x)))

# Extract patients with E1xx diabetes designation via ICD 10
betes_conditions_icd10 <- c("E100","E101","E102","E103","E104","E105","E106","E108","E109",
                              "E110","E111","E112","E113","E114","E115","E116","E118","E119",
                              "E120","E121","E122","E123","E124","E125","E126","E128","E129",
                              "E130","E131","E132","E133","E134","E135","E136","E138","E139",
                              "E080","E081","E082","E083","E084","E085","E086","E088","E089",
                              "E090","E091","E092","E093","E094","E095","E096","E098","E099")
#diabetes_icd10_e1x <- which(rowSums(sapply(my_ukb_data[,col_main_icd10],"%in%", betes_conditions_icd10))>0)
diabetes_icd10_e1x <- which(rowSums(sapply(my_ukb_data[,col_second_icd10],"%in%", betes_conditions_icd10))>0)
#diabetes_icd10_e1x <- which(rowSums(sapply(my_ukb_data[,col_disease_icd10],"%in%", betes_conditions_icd10))>0)
paste0("# with ICD10 diabetes ", length(diabetes_icd10_e1x))

# Extract patients with E10x T1D designation via ICD 10
t1d_conditions_icd10 <- c("E100","E101","E102","E103","E104","E105","E106","E108","E109")
#t1d_icd10_e10x <- which(rowSums(sapply(my_ukb_data[,col_main_icd10],"%in%", t1d_conditions_icd10))>0)
t1d_icd10_e10x <- which(rowSums(sapply(my_ukb_data[,col_second_icd10],"%in%", t1d_conditions_icd10))>0)
#t1d_icd10_e10x <- which(rowSums(sapply(my_ukb_data[,col_disease_icd10],"%in%", t1d_conditions_icd10))>0)
paste0("# with ICD10 T1D ", length(t1d_icd10_e10x))

# Extract patients with E11x T2D designation via ICD 10
t2d_conditions_icd10 <- c("E110","E111","E112","E113","E114","E115","E116","E118","E119")
#t2d_icd10_e11x <- which(rowSums(sapply(my_ukb_data[,col_main_icd10],"%in%", t2d_conditions_icd10))>0)
t2d_icd10_e11x <- which(rowSums(sapply(my_ukb_data[,col_second_icd10],"%in%", t2d_conditions_icd10))>0)
#t2d_icd10_e11x <- which(rowSums(sapply(my_ukb_data[,col_disease_icd10],"%in%", t2d_conditions_icd10))>0)
paste0("# with ICD10 T2D ", length(t2d_icd10_e11x))

# CONTROLS ICD10
# Extract patients WITHOUT ICD10 AP or CP designation
control_icd10_total <- setdiff(all_indices, panc_idc10_ix)
paste0("# controls ", length(control_icd10_total))

# Grab samples of control population
s <- 500
set.seed(5750)
control_icd10_sample500 <- sample(control_icd10_total, s, replace = FALSE, prob = NULL)
s <- 2000
set.seed(5750)
control_icd10_sample2000 <- sample(control_icd10_total, s, replace = FALSE, prob = NULL)

# Test for correctness
(nrow(my_ukb_data) - length(control_icd10_total)) == (length(ap_icd10_k85x) + 
                                                     length(cp_icd10_k86x) - length(intersect(ap_icd10_k85x,cp_icd10_k86x)))
```